// <auto-generated />
using System;
using Hoard.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoard.Core.Data.Migrations
{
    [DbContext(typeof(HoardContext))]
    [Migration("20260124172034_MissingPrecision")]
    partial class MissingPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AccountTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AccountType", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.AssetClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AssetClassId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetClass", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.AssetSubclass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AssetSubclassId");

                    b.Property<int>("AssetClassId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetClassId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetSubclass", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(3)")
                        .HasColumnName("CurrencyId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HoldingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("AccountId", "InstrumentId", "AsOfDate")
                        .IsUnique();

                    b.ToTable("Holding", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.HoldingValuation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HoldingValuationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HoldingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId")
                        .IsUnique();

                    b.ToTable("HoldingValuation", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstrumentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetSubclassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<bool>("EnableNewsUpdates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnablePriceUpdates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("InstrumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Isin")
                        .HasColumnType("char(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NewsImportStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TickerDisplay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TickerNewsUpdates")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TickerPriceUpdates")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssetSubclassId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasFilter("[Isin] IS NOT NULL");

                    b.ToTable("Instrument", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("InstrumentTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsCash")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFxPair")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InstrumentType", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsArticleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceArticleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("Source", "SourceArticleId")
                        .IsUnique();

                    b.ToTable("NewsArticle", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortfolioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PortfolioPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortfolioPerformanceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnnualisedReturn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CashValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PreviousValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RealisedGain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Return10Y")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Return1D")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return1M")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return1W")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return1Y")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return3M")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return3Y")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return5Y")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return6M")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ReturnAllTime")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ReturnYtd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnrealisedGain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValueChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValueChange1Y")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId")
                        .IsUnique();

                    b.ToTable("PortfolioPerformance", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PortfolioSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortfolioSnapshotId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Churn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CountTrades")
                        .HasColumnType("int");

                    b.Property<decimal>("EndValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Return")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StartValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBuys")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDealingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDepositEmployer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDepositIncomeTaxReclaim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDepositPersonal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDepositTransferIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFxCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncomeDividends")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncomeInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncomeLoyaltyBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncomePromotion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPtmLevy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSells")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalStampDuty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithdrawals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("ValueChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioSnapshot", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PortfolioValuation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PortfolioValuationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "AsOfDate")
                        .IsUnique();

                    b.ToTable("PortfolioValuation", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PositionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("date");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PositionPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PositionPerformanceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnnualisedReturn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostBasis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PreviousValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RealisedGain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Return10Y")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Return1D")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return1M")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return1W")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return1Y")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return3M")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return3Y")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return5Y")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Return6M")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ReturnAllTime")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ReturnYtd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UnrealisedGain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValueChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValueChange1Y")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("PositionPerformance", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PriceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdjustedClose")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "AsOfDate")
                        .IsUnique();

                    b.ToTable("Price", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuoteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ask")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Bid")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FiftyTwoWeekHigh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FiftyTwoWeekLow")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<decimal>("RegularMarketChange")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RegularMarketChangePercent")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("RegularMarketPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.ToTable("Quote", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.TargetAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TargetAllocationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetSubclassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Target")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetSubclassId");

                    b.HasIndex("PortfolioId", "AssetSubclassId")
                        .IsUnique();

                    b.ToTable("TargetAllocation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Target_0_100", "[Target] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("ContractNoteReference")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("DealingCharge")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("FxCharge")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PtmLevy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("StampDuty")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Units")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Date");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TransactionTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionType", (string)null);
                });

            modelBuilder.Entity("PortfolioAccount", b =>
                {
                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("PortfolioId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("PortfolioAccount");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Account", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.AssetSubclass", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.AssetClass", "AssetClass")
                        .WithMany("Subclasses")
                        .HasForeignKey("AssetClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetClass");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Holding", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.HoldingValuation", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Holding", "Holding")
                        .WithOne("Valuation")
                        .HasForeignKey("Hoard.Core.Domain.Entities.HoldingValuation", "HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Instrument", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.AssetSubclass", "AssetSubclass")
                        .WithMany()
                        .HasForeignKey("AssetSubclassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Domain.Entities.InstrumentType", "InstrumentType")
                        .WithMany()
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetSubclass");

                    b.Navigation("Currency");

                    b.Navigation("InstrumentType");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PortfolioPerformance", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Portfolio", "Portfolio")
                        .WithOne("Performance")
                        .HasForeignKey("Hoard.Core.Domain.Entities.PortfolioPerformance", "PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PortfolioSnapshot", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PortfolioValuation", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Position", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.PositionPerformance", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Position", "Position")
                        .WithOne("Performance")
                        .HasForeignKey("Hoard.Core.Domain.Entities.PositionPerformance", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Price", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Quote", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Instrument", "Instrument")
                        .WithOne("Quote")
                        .HasForeignKey("Hoard.Core.Domain.Entities.Quote", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.TargetAllocation", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.AssetSubclass", "AssetSubclass")
                        .WithMany()
                        .HasForeignKey("AssetSubclassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("AssetTargets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetSubclass");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hoard.Core.Domain.Entities.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Instrument");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("PortfolioAccount", b =>
                {
                    b.HasOne("Hoard.Core.Domain.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Domain.Entities.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.AssetClass", b =>
                {
                    b.Navigation("Subclasses");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Holding", b =>
                {
                    b.Navigation("Valuation");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("AssetTargets");

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("Hoard.Core.Domain.Entities.Position", b =>
                {
                    b.Navigation("Performance");
                });
#pragma warning restore 612, 618
        }
    }
}
