name: Build, Test, and Publish Hoard Containers

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/server/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}/hoard
  BUILD_CONFIGURATION: Release

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/server
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore solution
        run: dotnet restore Hoard.sln

      - name: Build
        run: dotnet build Hoard.sln -c ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test Hoard.sln -c ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal

      - name: Log in to GitHub Container Registry
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      # Build and push API image
      - name: Build and push API image
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: src/server
          file: src/server/Hoard.Api/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-api:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Bus image
      - name: Build and push Bus image
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: src/server
          file: src/server/Hoard.Bus/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-bus:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-bus:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Scheduler image
      - name: Build and push Scheduler image
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: src/server
          file: src/server/Hoard.Scheduler/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-scheduler:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-scheduler:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
